// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Daniel Eklund

//! The consolidated grammar's build contract.
//!
//! One pinned Tree-sitter CLI, named once in the Makefile and ENFORCED here
//! rather than hinted at: a parser generated by a different CLI does not match
//! the `tree-sitter-c2rust` runtime's ABI, and the failure that produces is far
//! from the cause.
//!
//! EVERYTHING THIS WRITES IS DERIVED, and generation is the only way it
//! exists. `parser.c`, `grammar.json` and `node-types.json` land in the
//! grammar's ignored `src/`; the typed Rust CST lands in `OUT_DIR` and never
//! appears in the tree at all. Nothing the generator writes is checked in, so
//! there is no second copy for the authored grammar to drift from.

#[path = "generator/typed_cst.rs"]
mod typed_cst;

use std::path::{Path, PathBuf};
use std::process::Command;

/// The pin lives in the Makefile. Two copies of a version that must agree is
/// one copy too many — a drifted second copy would confidently lie.
fn pinned_version(workspace_root: &Path) -> String {
    let mk = std::fs::read_to_string(workspace_root.join("Makefile"))
        .expect("the Makefile carries the tree-sitter pin");
    mk.lines()
        // The ASSIGNMENT, not the `$(...)` references in the recipes: Make puts
        // assignments at column 0 and recipe lines behind a tab.
        .find(|l| l.starts_with("TREE_SITTER_EXPECTED_VERSION"))
        .and_then(|l| l.split_once('='))
        .map(|(_, v)| v.trim().to_string())
        .filter(|v| !v.is_empty())
        .expect("TREE_SITTER_EXPECTED_VERSION is missing from the Makefile")
}

fn installed_version() -> Option<String> {
    let out = Command::new("tree-sitter").arg("--version").output().ok()?;
    String::from_utf8_lossy(&out.stdout)
        .split_whitespace()
        .nth(1)
        .map(str::to_string)
}

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crates/<pkg> sits two levels under the workspace root")
        .to_path_buf();

    let grammar_dir = workspace_root.join("grammar");
    let src_dir = grammar_dir.join("src");
    let parser_c = src_dir.join("parser.c");
    let node_types = src_dir.join("node-types.json");

    for input in [
        "grammar.js",
        "tokens.js",
        "conflicts.js",
        "tree-sitter.json",
    ] {
        println!(
            "cargo:rerun-if-changed={}",
            grammar_dir.join(input).display()
        );
    }
    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join("Makefile").display()
    );
    // The DERIVED output too. Cargo re-runs a script when a watched path is
    // missing, so a cleaned or hand-deleted `src/` regenerates instead of
    // linking whatever the last build left — or failing to find it at all.
    println!("cargo:rerun-if-changed={}", parser_c.display());
    println!("cargo:rerun-if-changed={}", node_types.display());

    if needs_generation(&grammar_dir, &parser_c, &node_types) {
        let pinned = pinned_version(&workspace_root);
        match installed_version() {
            Some(found) if found == pinned => {}
            Some(found) => panic!(
                "\n\ntree-sitter CLI {found} is on PATH; the pin is {pinned}.\n\
                 The generated parser must come from the pinned CLI — it has to match\n\
                 the tree-sitter-c2rust runtime's ABI.\n\n  \
                 cargo install tree-sitter-cli --version {pinned} --force\n"
            ),
            None => panic!(
                "\n\ntree-sitter CLI {pinned} is not on PATH.\n\n  \
                 cargo install tree-sitter-cli --version {pinned}\n\n\
                 The consolidated grammar is generated, not checked in.\n"
            ),
        }

        let out = Command::new("tree-sitter")
            .arg("generate")
            .current_dir(&grammar_dir)
            .output()
            .expect("running the pinned tree-sitter CLI");
        if !out.status.success() {
            panic!(
                "\n\ntree-sitter generate failed in grammar\n\n--- stdout ---\n{}\n--- stderr ---\n{}\n",
                String::from_utf8_lossy(&out.stdout),
                String::from_utf8_lossy(&out.stderr),
            );
        }
    }

    cc::Build::new()
        .include(&src_dir)
        .file(&parser_c)
        .warnings(false)
        .compile("tree-sitter-delightql-consolidated");

    let json = std::fs::read_to_string(&node_types).expect("node-types.json after generation");
    let generated = typed_cst::generate(&json);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out_dir.join("typed_cst.rs"), generated).expect("writing the typed CST");
}

/// Regenerate when the derived output is absent or older than any authored
/// input. Comparing timestamps rather than always regenerating keeps an
/// ordinary rebuild from paying for a 13 MB parser it already has.
fn needs_generation(grammar_dir: &Path, parser_c: &Path, node_types: &Path) -> bool {
    let Ok(parser_time) = std::fs::metadata(parser_c).and_then(|m| m.modified()) else {
        return true;
    };
    if !node_types.exists() {
        return true;
    }
    ["grammar.js", "tokens.js", "conflicts.js"]
        .iter()
        .any(|input| {
            std::fs::metadata(grammar_dir.join(input))
                .and_then(|m| m.modified())
                .map(|t| t > parser_time)
                .unwrap_or(true)
        })
}
