// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Daniel Eklund

//! The consolidated grammar's build contract.
//!
//! One pinned Tree-sitter CLI, named once in the Makefile and ENFORCED here
//! rather than hinted at: a parser generated by a different CLI does not match
//! the `tree-sitter-c2rust` runtime's ABI, and the failure that produces is far
//! from the cause.
//!
//! EVERYTHING THIS WRITES IS DERIVED, and generation is the only way it
//! exists. `parser.c`, `grammar.json` and `node-types.json` land in the
//! grammar's ignored `src/`; the typed Rust CST lands in `OUT_DIR` and never
//! appears in the tree at all. Nothing the generator writes is checked in, so
//! there is no second copy for the authored grammar to drift from.

#[path = "generator/typed_cst.rs"]
mod typed_cst;

use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::Command;

/// The pin lives in the Makefile. Two copies of a version that must agree is
/// one copy too many — a drifted second copy would confidently lie.
fn pinned_version(workspace_root: &Path) -> String {
    let mk = std::fs::read_to_string(workspace_root.join("Makefile"))
        .expect("the Makefile carries the tree-sitter pin");
    mk.lines()
        // The ASSIGNMENT, not the `$(...)` references in the recipes: Make puts
        // assignments at column 0 and recipe lines behind a tab.
        .find(|l| l.starts_with("TREE_SITTER_EXPECTED_VERSION"))
        .and_then(|l| l.split_once('='))
        .map(|(_, v)| v.trim().to_string())
        .filter(|v| !v.is_empty())
        .expect("TREE_SITTER_EXPECTED_VERSION is missing from the Makefile")
}

fn installed_version() -> Option<String> {
    let out = Command::new("tree-sitter").arg("--version").output().ok()?;
    String::from_utf8_lossy(&out.stdout)
        .split_whitespace()
        .nth(1)
        .map(str::to_string)
}

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crates/<pkg> sits two levels under the workspace root")
        .to_path_buf();

    let grammar_dir = workspace_root.join("grammar");
    let src_dir = grammar_dir.join("src");
    let parser_c = src_dir.join("parser.c");
    let node_types = src_dir.join("node-types.json");

    for input in [
        "grammar.js",
        "tokens.js",
        "conflicts.js",
        "tree-sitter.json",
    ] {
        println!(
            "cargo:rerun-if-changed={}",
            grammar_dir.join(input).display()
        );
    }
    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join("Makefile").display()
    );
    // The DERIVED output too. Cargo re-runs a script when a watched path is
    // missing, so a cleaned or hand-deleted `src/` regenerates instead of
    // linking whatever the last build left — or failing to find it at all.
    println!("cargo:rerun-if-changed={}", parser_c.display());
    println!("cargo:rerun-if-changed={}", node_types.display());

    if needs_generation(&grammar_dir, &parser_c, &node_types) {
        let pinned = pinned_version(&workspace_root);
        match installed_version() {
            Some(found) if found == pinned => {}
            Some(found) => panic!(
                "\n\ntree-sitter CLI {found} is on PATH; the pin is {pinned}.\n\
                 The generated parser must come from the pinned CLI — it has to match\n\
                 the tree-sitter-c2rust runtime's ABI.\n\n  \
                 cargo install tree-sitter-cli --version {pinned} --force\n"
            ),
            None => panic!(
                "\n\ntree-sitter CLI {pinned} is not on PATH.\n\n  \
                 cargo install tree-sitter-cli --version {pinned}\n\n\
                 The consolidated grammar is generated, not checked in.\n"
            ),
        }

        let out = Command::new("tree-sitter")
            .arg("generate")
            .current_dir(&grammar_dir)
            .output()
            .expect("running the pinned tree-sitter CLI");
        if !out.status.success() {
            panic!(
                "\n\ntree-sitter generate failed in grammar\n\n--- stdout ---\n{}\n--- stderr ---\n{}\n",
                String::from_utf8_lossy(&out.stdout),
                String::from_utf8_lossy(&out.stderr),
            );
        }
    }

    cc::Build::new()
        .include(&src_dir)
        .file(&parser_c)
        .warnings(false)
        .compile("tree-sitter-delightql-consolidated");

    let json = std::fs::read_to_string(&node_types).expect("node-types.json after generation");
    let generated = typed_cst::generate(&json);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out_dir.join("typed_cst.rs"), generated).expect("writing the typed CST");

    let facts = minted_facts(&workspace_root, &parser_c, &node_types);
    std::fs::write(out_dir.join("minted_facts.rs"), facts).expect("writing the minted facts");
}

/// The build identity the parser evidence records: the grammar fingerprint
/// and the parser-runtime spelling, as `pub const` items.
///
/// The fingerprint is SHA-256 over both generated artifacts with unambiguous
/// length framing — each artifact contributes its byte length as 8 big-endian
/// bytes, then its content, `parser.c` first — so no concatenation of two
/// different artifact pairs can collide by shifting bytes across the seam.
///
/// The runtime spelling comes from the lockfile's resolved
/// `tree-sitter-c2rust` version — the exact runtime this build links — with
/// the workspace manifest's pin as the fallback for a lockless checkout.
fn minted_facts(workspace_root: &Path, parser_c: &Path, node_types: &Path) -> String {
    let mut hasher = Sha256::new();
    for artifact in [parser_c, node_types] {
        let bytes = std::fs::read(artifact).expect("generated artifact for fingerprinting");
        hasher.update((bytes.len() as u64).to_be_bytes());
        hasher.update(&bytes);
    }
    let fingerprint: String = hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();

    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join("Cargo.lock").display()
    );
    let runtime_version = std::fs::read_to_string(workspace_root.join("Cargo.lock"))
        .ok()
        .and_then(|lock| {
            let mut lines = lock.lines();
            while let Some(line) = lines.next() {
                if line.trim() == "name = \"tree-sitter-c2rust\"" {
                    return lines
                        .next()
                        .and_then(|v| v.trim().strip_prefix("version = \"")?.strip_suffix('"').map(str::to_string));
                }
            }
            None
        })
        .unwrap_or_else(|| {
            let manifest = std::fs::read_to_string(workspace_root.join("Cargo.toml"))
                .expect("the workspace manifest pins the parser runtime");
            manifest
                .lines()
                .find(|l| l.contains("tree-sitter-c2rust"))
                .and_then(|l| l.split("version = \"").nth(1))
                .and_then(|rest| rest.split('"').next())
                .expect("the workspace manifest names the tree-sitter-c2rust version")
                .to_string()
        });

    format!(
        "/// SHA-256 over the length-framed generated `parser.c` and\n\
         /// `node-types.json` — the identity of the grammar this build parses with.\n\
         pub const GRAMMAR_FINGERPRINT: &str = \"{fingerprint}\";\n\
         /// The parser runtime this build links, as resolved by the lockfile.\n\
         pub const PARSER_RUNTIME: &str = \"tree-sitter-c2rust {runtime_version}\";\n"
    )
}

/// Regenerate when the derived output is absent or older than any authored
/// input. Comparing timestamps rather than always regenerating keeps an
/// ordinary rebuild from paying for a 13 MB parser it already has.
fn needs_generation(grammar_dir: &Path, parser_c: &Path, node_types: &Path) -> bool {
    let Ok(parser_time) = std::fs::metadata(parser_c).and_then(|m| m.modified()) else {
        return true;
    };
    if !node_types.exists() {
        return true;
    }
    ["grammar.js", "tokens.js", "conflicts.js"]
        .iter()
        .any(|input| {
            std::fs::metadata(grammar_dir.join(input))
                .and_then(|m| m.modified())
                .map(|t| t > parser_time)
                .unwrap_or(true)
        })
}
