// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Daniel Eklund

//! The consolidated grammar's build contract.
//!
//! One pinned Tree-sitter CLI, named once in the Makefile and ENFORCED here
//! rather than hinted at: the CLI version is the runtime version, and a
//! parser generated by another CLI may carry an ABI the linked runtime does
//! not accept, with a failure far from the cause. The CLI must be installed
//! `--locked`: an unlocked install links a floating generator, and the
//! version it prints then says nothing about the tables it writes. No check
//! of a binary can see how it was installed, so this script runs only the
//! one `make ensure-tree-sitter` installs `--locked` under the Makefile's
//! TREE_SITTER_ROOT — never a `tree-sitter` found on PATH.
//!
//! EVERYTHING THIS WRITES IS DERIVED, and generation is the only way it
//! exists. `parser.c`, `grammar.json` and `node-types.json` land in the
//! grammar's ignored `src/`; the typed Rust CST lands in `OUT_DIR` and never
//! appears in the tree at all. Nothing the generator writes is checked in, so
//! there is no second copy for the authored grammar to drift from.

#[path = "generator/typed_cst.rs"]
mod typed_cst;
#[path = "generator/tuple.rs"]
mod tuple;

use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::Command;

/// The pin and the CLI's install root live in the Makefile, which installs
/// the CLI where this script runs it from. Two copies of a value that must
/// agree is one copy too many — a drifted second copy would confidently lie.
fn makefile_value(workspace_root: &Path, name: &str) -> String {
    let mk = std::fs::read_to_string(workspace_root.join("Makefile"))
        .expect("the Makefile carries the tree-sitter pin and install root");
    tuple::makefile_assignment(&mk, name)
        .unwrap_or_else(|| panic!("the Makefile must assign {name} once, to a literal"))
}

/// Where `cargo install --root` puts the CLI under the Makefile's root.
fn pinned_cli(workspace_root: &Path) -> PathBuf {
    workspace_root
        .join(makefile_value(workspace_root, "TREE_SITTER_ROOT"))
        .join("bin")
        .join(format!("tree-sitter{}", std::env::consts::EXE_SUFFIX))
}

fn installed_version(cli: &Path) -> Option<String> {
    let out = Command::new(cli).arg("--version").output().ok()?;
    String::from_utf8_lossy(&out.stdout)
        .split_whitespace()
        .nth(1)
        .map(str::to_string)
}

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crates/<pkg> sits two levels under the workspace root")
        .to_path_buf();

    // THE TUPLE IS JUDGED BEFORE ANYTHING IS COMPILED, whether or not the
    // grammar needs regenerating: a runtime moved under fresh derived files
    // is a split the generation check alone would never see.
    let runtime_version = judged_runtime(&workspace_root);

    let grammar_dir = workspace_root.join("grammar");
    let src_dir = grammar_dir.join("src");
    let parser_c = src_dir.join("parser.c");
    let node_types = src_dir.join("node-types.json");

    for input in [
        "grammar.js",
        "tokens.js",
        "conflicts.js",
        "tree-sitter.json",
    ] {
        println!(
            "cargo:rerun-if-changed={}",
            grammar_dir.join(input).display()
        );
    }
    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join("Makefile").display()
    );
    // The DERIVED output too. Cargo re-runs a script when a watched path is
    // missing, so a cleaned or hand-deleted `src/` regenerates instead of
    // linking whatever the last build left — or failing to find it at all.
    println!("cargo:rerun-if-changed={}", parser_c.display());
    println!("cargo:rerun-if-changed={}", node_types.display());

    if needs_generation(&grammar_dir, &parser_c, &node_types) {
        let pinned = runtime_version.clone();
        let cli = pinned_cli(&workspace_root);
        match installed_version(&cli) {
            Some(found) if found == pinned => {}
            Some(found) => panic!(
                "\n\nthe tree-sitter CLI at {} is {found}; the pin is {pinned}.\n\
                 The generated parser must come from the pinned CLI — it has to match\n\
                 the tree-sitter runtime's ABI.\n\n  \
                 make ensure-tree-sitter\n",
                cli.display()
            ),
            None => panic!(
                "\n\nthe pinned tree-sitter CLI {pinned} is not installed at {}.\n\n  \
                 make ensure-tree-sitter\n\n\
                 The consolidated grammar is generated, not checked in.\n",
                cli.display()
            ),
        }

        // `native` evaluates grammar.js in the QuickJS the CLI carries, so
        // generation needs no node.
        let out = Command::new(&cli)
            .args(["generate", "--js-runtime", "native"])
            .current_dir(&grammar_dir)
            .output()
            .expect("running the pinned tree-sitter CLI");
        if !out.status.success() {
            panic!(
                "\n\ntree-sitter generate failed in grammar\n\n--- stdout ---\n{}\n--- stderr ---\n{}\n",
                String::from_utf8_lossy(&out.stdout),
                String::from_utf8_lossy(&out.stderr),
            );
        }
    }

    let mut parser = cc::Build::new();
    parser.include(&src_dir).file(&parser_c).warnings(false);
    // wasm32-unknown-unknown has no libc: the parser's C headers come from
    // the tree-sitter-language crate, which publishes them to its direct
    // dependents. The runtime defines every symbol they declare.
    if std::env::var("TARGET").is_ok_and(|t| t.starts_with("wasm32-unknown")) {
        let headers = std::env::var("DEP_TREE_SITTER_LANGUAGE_WASM_HEADERS")
            .expect("tree-sitter-language publishes the wasm32 C headers to its dependents");
        parser.include(headers);
    }
    parser.compile("tree-sitter-delightql-consolidated");

    let json = std::fs::read_to_string(&node_types).expect("node-types.json after generation");
    let generated = typed_cst::generate(&json);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out_dir.join("typed_cst.rs"), generated).expect("writing the typed CST");

    let facts = minted_facts(&workspace_root, &parser_c, &node_types, &runtime_version);
    std::fs::write(out_dir.join("minted_facts.rs"), facts).expect("writing the minted facts");
}

/// The build identity the parser evidence records: the grammar fingerprint
/// and the parser-runtime spelling, as `pub const` items.
///
/// The fingerprint is SHA-256 over both generated artifacts with unambiguous
/// length framing — each artifact contributes its byte length as 8 big-endian
/// bytes, then its content, `parser.c` first — so no concatenation of two
/// different artifact pairs can collide by shifting bytes across the seam.
///
/// The runtime spelling is the judged tuple's one version.
fn minted_facts(workspace_root: &Path, parser_c: &Path, node_types: &Path, runtime_version: &str) -> String {
    let mut hasher = Sha256::new();
    for artifact in [parser_c, node_types] {
        let bytes = std::fs::read(artifact).expect("generated artifact for fingerprinting");
        hasher.update((bytes.len() as u64).to_be_bytes());
        hasher.update(&bytes);
    }
    let fingerprint: String = hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();

    let _ = workspace_root;
    format!(
        "/// SHA-256 over the length-framed generated `parser.c` and\n\
         /// `node-types.json` — the identity of the grammar this build parses with.\n\
         pub const GRAMMAR_FINGERPRINT: &str = \"{fingerprint}\";\n\
         /// The parser runtime this build links, as resolved by the lockfile.\n\
         pub const PARSER_RUNTIME: &str = \"tree-sitter {runtime_version}\";\n"
    )
}

/// The one version the generator pin, the linked runtime and the linked
/// highlighter share — read from the Makefile and the lockfile (the manifest's
/// exact pins stand in for a lockless checkout) and judged by
/// `generator/tuple.rs`. A split refuses the build here, with the reason.
fn judged_runtime(workspace_root: &Path) -> String {
    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join("Cargo.lock").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join("Cargo.toml").display()
    );
    let generator_pin = makefile_value(workspace_root, "TREE_SITTER_EXPECTED_VERSION");
    let (runtimes, highlighters) = match std::fs::read_to_string(workspace_root.join("Cargo.lock")) {
        Ok(lock) => (
            tuple::lockfile_versions(&lock, "tree-sitter"),
            tuple::lockfile_versions(&lock, "tree-sitter-highlight"),
        ),
        Err(_) => {
            let manifest = std::fs::read_to_string(workspace_root.join("Cargo.toml"))
                .expect("the workspace manifest pins the parser runtime");
            (
                tuple::manifest_exact_pin(&manifest, "tree-sitter").into_iter().collect(),
                tuple::manifest_exact_pin(&manifest, "tree-sitter-highlight").into_iter().collect(),
            )
        }
    };
    let facts = tuple::TupleFacts { generator_pin, runtimes, highlighters };
    match tuple::judge(&facts) {
        Ok(version) => version,
        Err(why) => panic!(
            "\n\nthe parser tuple is split: {why}\n\
             Move TREE_SITTER_EXPECTED_VERSION (Makefile), `tree-sitter` and\n\
             `tree-sitter-highlight` (Cargo.toml) together, then `cargo update -p tree-sitter`.\n"
        ),
    }
}

/// Regenerate when the derived output is absent or older than any authored
/// input. Comparing timestamps rather than always regenerating keeps an
/// ordinary rebuild from paying for a 13 MB parser it already has.
fn needs_generation(grammar_dir: &Path, parser_c: &Path, node_types: &Path) -> bool {
    let Ok(parser_time) = std::fs::metadata(parser_c).and_then(|m| m.modified()) else {
        return true;
    };
    if !node_types.exists() {
        return true;
    }
    ["grammar.js", "tokens.js", "conflicts.js"]
        .iter()
        .any(|input| {
            std::fs::metadata(grammar_dir.join(input))
                .and_then(|m| m.modified())
                .map(|t| t > parser_time)
                .unwrap_or(true)
        })
}
