// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Daniel Eklund
//! Resolver scope and CTE provenance that is not column identity.

/// Whether a CTE was defined by the user or generated by the compiler
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CteOrigin {
    /// User-defined CTE (WITH clause or DDL view)
    UserDefined,
    /// Compiler-generated CTE (HO expansion, pipe materialization)
    CompilerGenerated,
}

impl Default for CteOrigin {
    fn default() -> Self {
        CteOrigin::UserDefined
    }
}
