use crate::pipeline::ast_addressed;
use crate::pipeline::asts::core::IdentityContext;

/// Structure to hold CPR law detection results
pub(crate) struct CprLawDetection {
    pub(crate) law1_qualified_columns: bool,
    #[allow(dead_code)]
    pub(crate) law2_alias_references: bool,
    #[allow(dead_code)]
    pub(crate) law3_forward_references: bool,
}

/// Check if a CTE name is an internal (compiler-generated) name.
///
/// Internal CTE names are generated by the HO view expansion and start with
/// `_ho_`. These CTEs have synthetic qualifiers that should not trigger law1.
/// User-defined CTEs (any other name) may have provenance bugs in join contexts,
/// so we don't suppress law1 for them.
fn is_internal_cte(name: &str) -> bool {
    name.starts_with("_ho_")
}

/// Check if a Fresh column has any non-internal-CTE named table in its
/// identity stack.
///
/// Returns true (triggers law1) if the provenance references a real table.
/// Returns false (suppresses law1) if all named tables are internal CTEs
/// or the provenance is all-Fresh (generated column with inherited qualifier).
fn column_has_external_table(
    col: &ast_addressed::ColumnMetadata,
    internal_cte_names: &std::collections::HashSet<&str>,
) -> bool {
    for identity in col.info.identity_stack() {
        match &identity.context {
            IdentityContext::OriginalTable {
                table: ast_addressed::TableName::Named(t),
                ..
            } => {
                if !internal_cte_names.contains(t.as_str()) {
                    return true;
                }
            }
            IdentityContext::PipeBarrier {
                previous_table: ast_addressed::TableName::Named(t),
                ..
            } => {
                if !internal_cte_names.contains(t.as_str()) {
                    return true;
                }
            }
            _ => {}
        }
        if let ast_addressed::TableName::Named(t) = &identity.table_qualifier {
            if !internal_cte_names.contains(t.as_str()) {
                return true;
            }
        }
    }
    false
}

/// Common logic for detecting CPR laws from the CprSchema
/// This uses information from the resolver rather than re-walking expressions
pub(crate) fn detect_cpr_laws(cpr_schema: &ast_addressed::CprSchema) -> CprLawDetection {
    // Extract column metadata from the schema
    let columns = match cpr_schema {
        ast_addressed::CprSchema::Resolved(cols) => cols,
        ast_addressed::CprSchema::Failed {
            resolved_columns, ..
        } => resolved_columns,
        ast_addressed::CprSchema::Unresolved(_) => {
            return CprLawDetection {
                law1_qualified_columns: false,
                law2_alias_references: false,
                law3_forward_references: false,
            };
        }
        ast_addressed::CprSchema::Unknown => {
            return CprLawDetection {
                law1_qualified_columns: false,
                law2_alias_references: false,
                law3_forward_references: false,
            };
        }
    };

    // Law 1: Check if any columns were qualified in the source.
    // The resolver sets was_qualified when it sees qualified references.
    //
    // Exclude columns whose qualifiers are synthetic from internal CTE
    // expansion (HO body pipes). Only internal CTEs (_ho_*) are trusted
    // for this exclusion — user-defined CTE provenance may be unreliable
    // in join contexts where columns from different tables can get
    // attributed to the same CTE.
    let qualified_cols: Vec<_> = columns
        .iter()
        .filter(|col| col.info.is_qualified().unwrap_or(false))
        .collect();

    let law1_qualified_columns = if qualified_cols.is_empty() {
        false
    } else {
        // Collect INTERNAL CTE names from any column's provenance.
        // Only internal names (_ho_*) are safe to use for law1 suppression.
        let internal_cte_names: std::collections::HashSet<&str> = columns
            .iter()
            .filter_map(|col| col.info.referenceable_cte_name())
            .filter(|name| is_internal_cte(name))
            .collect();

        if internal_cte_names.is_empty() {
            // No internal CTEs — use original behavior: any qualified
            // column triggers law1.
            true
        } else {
            // Internal CTE context (HO body pipe). Exclude columns
            // that are in the internal CTE scope:
            //
            // 1. Column has internal CTE provenance directly
            // 2. Column's fq_table name matches an internal CTE name
            // 3. Column is Fresh and its identity stack traces through
            //    an internal CTE (e.g., `met` after pipe barrier has
            //    PipeBarrier.previous_table = internal CTE name)
            //
            // Only trigger law1 if a qualified column is NOT in any
            // internal CTE scope.
            qualified_cols.iter().any(|col| {
                // Check if column has internal CTE provenance
                if let Some(cte) = col.info.referenceable_cte_name() {
                    if is_internal_cte(cte) {
                        return false;
                    }
                }
                match &col.fq_table.name {
                    ast_addressed::TableName::Named(t) => {
                        !internal_cte_names.contains(t.as_str())
                    }
                    ast_addressed::TableName::Fresh => {
                        column_has_external_table(col, &internal_cte_names)
                    }
                }
            })
        }
    };

    // Law 2: Check if WHERE clause references projection aliases
    let law2_alias_references = false;

    // Law 3: Check for forward references in projections
    let law3_forward_references = false;

    CprLawDetection {
        law1_qualified_columns,
        law2_alias_references,
        law3_forward_references,
    }
}
