// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Daniel Eklund
//! Metadata types for expressions
//! FilterOrigin, SetOperator, TreeGroupLocation, CteRequirements

use super::super::{Phase, Unresolved};
use super::domain::DomainExpression;
use crate::{lispy::ToLispy, ToLispy};

/// Tracks the semantic origin of a filter condition
/// This metadata preserves WHY a filter exists, enabling correct SQL generation
#[derive(Debug, Clone, PartialEq, Eq, ToLispy, Default)]
pub enum FilterOrigin {
    /// User wrote explicit WHERE clause or sigma condition
    #[default]
    UserWritten,
    /// Generated from a positional-pattern literal constraint. The source
    /// scope is recorded when the resolver constructs the filter; later
    /// phases must not infer it from the predicate's references or position.
    PositionalLiteral { source: crate::names::ScopeId },
    /// Generated by query optimizer or other transformations
    Generated,
    /// Generated from HO ground scalar filtering. The squished relation includes
    /// `_label_N` columns the slot row's constraints compare. These columns
    /// must be stripped from the final output (they are hygienic implementation
    /// details, not part of the view's logical schema).
    HoGroundScalar,
}

/// Set operation types with principled semantics
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SetOperator {
    /// || - Pure positional UNION ALL (align by position)
    UnionAllPositional,
    /// ; - UNION CORRESPONDING (align by name, NULL pad missing)
    UnionCorresponding,
    /// |;| - Smart Union All (same names, different order allowed)
    SmartUnionAll,
    /// - (minus) EXCEPT CORRESPONDING (rows in left not in right, by name)
    MinusCorresponding,
}

impl crate::lispy::ToLispy for SetOperator {
    fn to_lispy(&self) -> String {
        match self {
            SetOperator::UnionAllPositional => "union_all_positional".to_string(),
            SetOperator::UnionCorresponding => "union_corresponding".to_string(),
            SetOperator::SmartUnionAll => "smart_union_all".to_string(),
            SetOperator::MinusCorresponding => "minus_corresponding".to_string(),
        }
    }
}

impl SetOperator {
    /// Whether this operator accumulates its arm's rows into the result.
    ///
    /// Minus does not: its arm is only ever probed, so a run of minus steps
    /// is a chain of binary subtractions, never one N-way operation.
    pub fn accumulates_arm_rows(self) -> bool {
        match self {
            SetOperator::UnionAllPositional
            | SetOperator::UnionCorresponding
            | SetOperator::SmartUnionAll => true,
            SetOperator::MinusCorresponding => false,
        }
    }
}

/// Location of a tree group in a group reduction specification
/// Determines whether tree group is in scalar or aggregate context
#[derive(Debug, Clone, Copy, PartialEq, Eq, ToLispy)]
pub enum TreeGroupLocation {
    /// Tree group appears in keys (before ~>)
    /// Context: Scalar - defines grouping keys, produces single JSON object
    /// Example: %({country, "people": ~> {...}} ~> count:(*))
    ///          ^ this tree group is InKeys
    InKeys,
    /// Tree group appears in reductions (after ~>)
    /// Context: Aggregate - produces JSON array
    /// Example: %(country ~> {first_name, last_name})
    ///                       ^ this tree group is InReductions
    InReductions,
}

/// Metadata for a nested member in a tree group CTE
#[derive(Debug, Clone, PartialEq, ToLispy)]
pub struct NestedMemberCteInfo {
    /// Key name for this nested member (e.g., "people", "orders")
    pub key: String,
}

/// CTE requirements computed by resolver for tree groups with nested reductions
/// This metadata guides the transformer to generate independent CTEs
#[derive(Debug, Clone, PartialEq, ToLispy)]
pub struct CteRequirements<P: Phase = Unresolved> {
    /// Whether this tree group needs a CTE
    /// True when tree group contains nested reductions ("key": ~> {...})
    pub needs_cte: bool,

    /// Accumulated grouping keys for CTE GROUP BY
    /// Includes outer reducing-by keys and this tree group's record dimensions.
    /// Each entry is (key_name, expression) where:
    /// - key_name is Some("level1") for GROUPING DRESS members
    /// - key_name is None for simple scalar fields
    /// Example: %(country ~> {status, "people": ~> {...}})
    ///   → accumulated_grouping_keys = [(None, country), (None, status)]
    /// Example: ~> {"level1": {country}, "cities": ~> {"level2": {city}, ...}}
    ///   → accumulated_grouping_keys = [(Some("level1"), {country}), (Some("level2"), {city})]
    pub accumulated_grouping_keys: Vec<(Option<String>, DomainExpression<P>)>,

    /// Keys to JOIN on (connects CTE to base table or outer CTE)
    /// Usually equals the outer keys keys
    /// Example: %(country, status ~> {age, "people": ~> {...}})
    ///   → join_keys = [country, status]
    pub join_keys: Vec<DomainExpression<P>>,

    /// Location in query (keys or reductions)
    /// Determines scalar vs aggregate context for transformation
    pub location: TreeGroupLocation,

    /// Metadata for each nested member
    pub nested_members_info: Vec<NestedMemberCteInfo>,
}

/// The analyzed tree group at one indexed position in a group reduction.
#[derive(Debug, Clone, PartialEq, ToLispy)]
#[lispy("tree_group_plan")]
pub struct TreeGroupPlan<P: Phase = Unresolved> {
    pub location: TreeGroupLocation,
    pub item_index: usize,
    pub requirements: CteRequirements<P>,
}

/// Lowering facts owned by the reduction that needs them.
#[derive(Debug, Clone, PartialEq, ToLispy)]
#[lispy("reduction_plan")]
pub struct ReductionPlan<P: Phase = Unresolved> {
    pub tree_groups: Vec<TreeGroupPlan<P>>,
}

impl<P: Phase> ReductionPlan<P> {
    pub fn empty() -> Self {
        Self {
            tree_groups: Vec::new(),
        }
    }

    pub fn needs_cte(&self, location: TreeGroupLocation, item_index: usize) -> bool {
        self.tree_groups.iter().any(|group| {
            group.location == location
                && group.item_index == item_index
                && group.requirements.needs_cte
        })
    }
}
