//! Metadata types for expressions
//! FilterOrigin, SetOperator, TreeGroupLocation, CteRequirements

use super::super::phase_box::PhaseBox;
use super::super::{Addressed, Refined, Resolved, Unresolved};
use super::domain::DomainExpression;
use crate::{lispy::ToLispy, PhaseConvert, ToLispy};
use serde::{Deserialize, Serialize};

/// Tracks the semantic origin of a filter condition
/// This metadata preserves WHY a filter exists, enabling correct SQL generation
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToLispy, Default)]
pub enum FilterOrigin {
    /// User wrote explicit WHERE clause or sigma condition
    #[default]
    UserWritten,
    /// Generated from positional pattern literal constraint
    /// e.g., reviews(_, _, _, 3, _) creates Filter with this origin
    /// The String contains the table name that had the positional pattern
    PositionalLiteral { source_table: String },
    /// Generated by query optimizer or other transformations
    Generated,
    /// Generated from HO ground scalar filtering. The squished relation includes
    /// `_label_N` columns for PatternResolver WHERE constraints. These columns
    /// must be stripped from the final output (they are hygienic implementation
    /// details, not part of the view's logical schema).
    HoGroundScalar { source_table: String },
}

/// Set operation types with principled semantics
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, ToLispy)]
pub enum SetOperator {
    /// || - Pure positional UNION ALL (align by position)
    UnionAllPositional,
    /// ; - UNION CORRESPONDING (align by name, NULL pad missing)
    UnionCorresponding,
    /// |;| - Smart Union All (same names, different order allowed)
    SmartUnionAll,
    /// - (minus) EXCEPT CORRESPONDING (rows in left not in right, by name)
    MinusCorresponding,
}

/// Location of a tree group in a modulo reduction specification
/// Determines whether tree group is in scalar or aggregate context
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToLispy)]
pub enum TreeGroupLocation {
    /// Tree group appears in reducing_by (before ~>)
    /// Context: Scalar - defines grouping keys, produces single JSON object
    /// Example: %({country, "people": ~> {...}} ~> count:(*))
    ///          ^ this tree group is InReducingBy
    InReducingBy,
    /// Tree group appears in reducing_on (after ~>)
    /// Context: Aggregate - produces JSON array
    /// Example: %(country ~> {first_name, last_name})
    ///                       ^ this tree group is InReducingOn
    InReducingOn,
}

/// Metadata for a nested member in a tree group CTE
/// Tracks which CTE column corresponds to which nested reduction
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ToLispy)]
pub struct NestedMemberCteInfo {
    /// Key name for this nested member (e.g., "people", "orders")
    pub key: String,
    /// Column name in the parent CTE that contains this nested reduction's result
    pub cte_column_name: String,
}

/// CTE requirements computed by resolver for tree groups with nested reductions
/// This metadata guides the transformer to generate independent CTEs
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ToLispy, PhaseConvert)]
pub struct CteRequirements<Phase = Unresolved> {
    /// Whether this tree group needs a CTE
    /// True when tree group contains nested reductions ("key": ~> {...})
    pub needs_cte: bool,

    /// Accumulated grouping keys for CTE GROUP BY
    /// Includes: outer reducing_by keys + this tree group's inner_grouping_keys
    /// Each entry is (key_name, expression) where:
    /// - key_name is Some("level1") for GROUPING DRESS members
    /// - key_name is None for simple scalar fields
    /// Example: %(country ~> {status, "people": ~> {...}})
    ///   → accumulated_grouping_keys = [(None, country), (None, status)]
    /// Example: ~> {"level1": {country}, "cities": ~> {"level2": {city}, ...}}
    ///   → accumulated_grouping_keys = [(Some("level1"), {country}), (Some("level2"), {city})]
    pub accumulated_grouping_keys: Vec<(Option<String>, DomainExpression<Phase>)>,

    /// Keys to JOIN on (connects CTE to base table or outer CTE)
    /// Usually equals the outer reducing_by keys
    /// Example: %(country, status ~> {age, "people": ~> {...}})
    ///   → join_keys = [country, status]
    pub join_keys: Vec<DomainExpression<Phase>>,

    /// Location in query (reducing_by or reducing_on)
    /// Determines scalar vs aggregate context for transformation
    pub location: TreeGroupLocation,

    /// Metadata for each nested member (for CTE column reference)
    /// Maps nested reduction keys to their CTE column names
    pub nested_members_info: Vec<NestedMemberCteInfo>,

    /// Pre-assigned CTE name from the addresser (Phase A+)
    /// None during builder/resolver/refiner, Some("_tg_0") after addresser walk.
    /// The transformer uses this instead of next_alias() when present.
    #[phase_convert(phantom)]
    pub cte_name: PhaseBox<Option<String>, Phase>,
}
