// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Daniel Eklund
use std::path::PathBuf;

fn main() {
    // Use CARGO_MANIFEST_DIR to find the workspace root reliably
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

    // --- Embedded stdlib auto-discovery ---
    generate_stdlib_manifest(&manifest_dir);
    // --- Embedded seed-program auto-discovery ---
    generate_seed_manifest(&manifest_dir);
}

/// Walk all top-level directories under autoload/ and generate src/stdlib_manifest.rs
/// with include_str!() entries. The directory name becomes the namespace prefix.
///
/// Directory structure mirrors namespaces directly:
///   autoload/std/info.dql            -> std::info
///   autoload/std/help.dql            -> std::help
///   autoload/std/util/string.dql     -> std::util::string
///   autoload/sys/build.dql           -> sys::build
///
/// Files already handled by dedicated loaders (sys/meta.dql) are excluded.
fn generate_stdlib_manifest(manifest_dir: &std::path::Path) {
    let autoload_dir = manifest_dir.join("autoload");
    let manifest_path = manifest_dir.join("src").join("stdlib_manifest.rs");

    // Rerun if anything under autoload/ changes
    println!("cargo:rerun-if-changed={}", autoload_dir.display());

    // Files with dedicated loaders — excluded from the manifest
    let excluded: &[&str] = &["sys::meta"];

    let mut modules: Vec<(String, PathBuf)> = Vec::new();

    if autoload_dir.exists() {
        // Walk each top-level subdirectory (std, sys, ...)
        if let Ok(entries) = std::fs::read_dir(&autoload_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    let prefix = path.file_name().unwrap().to_string_lossy().to_string();
                    collect_dql_files(&path, &path, &prefix, &mut modules);
                }
            }
        }
        // Remove excluded modules
        modules.retain(|(ns, _)| !excluded.contains(&ns.as_str()));
        modules.sort_by(|a, b| a.0.cmp(&b.0));
    }

    // Build content in memory first (write-if-changed pattern)
    let mut content = String::new();
    use std::fmt::Write as FmtWrite;
    writeln!(content, "// AUTO-GENERATED by build.rs -- do not edit").unwrap();
    writeln!(content, "pub const STDLIB_MODULES: &[(&str, &str)] = &[").unwrap();
    for (namespace, path) in &modules {
        // Path relative to manifest_dir for include_str!()
        let rel = path
            .strip_prefix(manifest_dir)
            .expect("file not under manifest dir");
        // include_str! paths are relative to the source file (src/stdlib_manifest.rs),
        // so we need ../ to get back to crate root
        let include_path = format!("../{}", rel.display());
        writeln!(
            content,
            "    (\"{}\", include_str!(\"{}\")),",
            namespace, include_path
        )
        .unwrap();

        // Track individual files for precise rerun triggers
        println!("cargo:rerun-if-changed={}", path.display());
    }
    writeln!(content, "];").unwrap();

    // Only write if content changed — prevents cross-platform formatting churn
    let existing = std::fs::read_to_string(&manifest_path).unwrap_or_default();
    if existing != content {
        std::fs::write(&manifest_path, &content).expect("Failed to write stdlib_manifest.rs");
        println!(
            "cargo:warning=Generated stdlib manifest with {} module(s)",
            modules.len()
        );
    }
}

/// Walk all .dql files under seed/ and generate src/seed_manifest.rs with
/// include_str!() entries. Unlike autoload/ (which INSTALLS definitions via
/// consult), seed/ programs RUN at startup for their effects — the manifest
/// name is just the file stem (e.g. seed/docs.dql -> "docs").
///
/// Seed programs run on EVERY startup (and every reinit), so each must be
/// idempotent. `doc!` qualifies: setting the same doc twice is a no-op-in-effect.
fn generate_seed_manifest(manifest_dir: &std::path::Path) {
    let seed_dir = manifest_dir.join("seed");
    let manifest_path = manifest_dir.join("src").join("seed_manifest.rs");

    // Rerun if anything under seed/ changes
    println!("cargo:rerun-if-changed={}", seed_dir.display());

    let mut programs: Vec<(String, PathBuf)> = Vec::new();

    if seed_dir.exists() {
        collect_dql_files(&seed_dir, &seed_dir, "", &mut programs);
        // collect_dql_files prepends "::" when prefix is empty; strip it.
        for (name, _) in programs.iter_mut() {
            *name = name.trim_start_matches("::").to_string();
        }
        programs.sort_by(|a, b| a.0.cmp(&b.0));
    }

    let mut content = String::new();
    use std::fmt::Write as FmtWrite;
    writeln!(content, "// AUTO-GENERATED by build.rs -- do not edit").unwrap();
    writeln!(content, "pub const SEED_PROGRAMS: &[(&str, &str)] = &[").unwrap();
    for (name, path) in &programs {
        let rel = path
            .strip_prefix(manifest_dir)
            .expect("file not under manifest dir");
        let include_path = format!("../{}", rel.display());
        writeln!(
            content,
            "    (\"{}\", include_str!(\"{}\")),",
            name, include_path
        )
        .unwrap();

        println!("cargo:rerun-if-changed={}", path.display());
    }
    writeln!(content, "];").unwrap();

    let existing = std::fs::read_to_string(&manifest_path).unwrap_or_default();
    if existing != content {
        std::fs::write(&manifest_path, &content).expect("Failed to write seed_manifest.rs");
        println!(
            "cargo:warning=Generated seed manifest with {} program(s)",
            programs.len()
        );
    }
}

/// Recursively collect .dql files under `base_dir`, computing namespaces from paths.
/// `prefix` is the top-level namespace (e.g. "std", "sys").
fn collect_dql_files(
    dir: &std::path::Path,
    base_dir: &std::path::Path,
    prefix: &str,
    modules: &mut Vec<(String, PathBuf)>,
) {
    // Watch this directory so new/removed files trigger a rebuild
    println!("cargo:rerun-if-changed={}", dir.display());

    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_dql_files(&path, base_dir, prefix, modules);
        } else if path.extension().map_or(false, |ext| ext == "dql") {
            // Compute namespace: strip base_dir prefix, strip .dql extension,
            // replace path separators with ::, prepend prefix::
            let rel = path
                .strip_prefix(base_dir)
                .expect("file not under base dir");
            let stem = rel.with_extension("");
            let ns_path = stem
                .components()
                .map(|c| c.as_os_str().to_string_lossy().to_string())
                .collect::<Vec<_>>()
                .join("::");
            let namespace = format!("{}::{}", prefix, ns_path);
            modules.push((namespace, path.clone()));
        }
    }
}
